apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: boots

build:
  local:
    push: true
    useDockerCLI: true
  artifacts:
    - image: homelab:9000/boots-db
      docker:
        dockerfile: docker/Dockerfile.db
        cacheFrom: [oven/bun:1.3.1-alpine, homelab:9000/boots-db]
    - image: homelab:9000/boots-api
      docker:
        dockerfile: docker/Dockerfile.prod
        target: release-api
        buildArgs:
          APP: api
        cacheFrom: [oven/bun:1.3.1-alpine, homelab:9000/boots-api]
      sync:
        manual:
          - src: 'apps/api/**/*.ts'
            strip: apps/api
            dest: '.'
          - src: 'apps/api/public/**/*'
            strip: apps/api/public
            dest: '.'
          - src: 'apps/api/package.json'
            strip: apps/api
            dest: '.'
    - image: homelab:9000/boots-web
      docker:
        dockerfile: docker/Dockerfile.prod
        target: release-web
        buildArgs:
          APP: web
        cacheFrom: [oven/bun:1.3.1-alpine, caddy:2.10.2-alpine, homelab:9000/boots-web]
      sync:
        manual:
          - src: 'apps/web/**/*.{ts,tsx,html}'
            strip: apps/web
            dest: '.'
          - src: 'apps/api/**/*.ts'
            strip: apps/api
            dest: ../api
          - src: 'apps/{api,web}/package.json'
            strip: apps
            dest: '..'
    

manifests:
  rawYaml:
    - k8s/namespace.yaml
    - k8s/cluster-issuer.yaml
    - k8s/gateway.yaml

deploy:
  helm:
    releases:
      - name: db
        chartPath: k8s/db
        namespace: boots
        createNamespace: true
        wait: true
        useHelmSecrets: true
        setValueTemplates:
          migration.image.repository: homelab:9000/boots-db
          migration.image.tag: '{{.IMAGE_TAG_homelab_9000_boots_db}}@{{.IMAGE_DIGEST_homelab_9000_boots_db}}'
      - name: api
        chartPath: apps/api/k8s
        namespace: boots
        useHelmSecrets: true
        setValueTemplates:
          image.repository: homelab:9000/boots-api
          image.tag: '{{.IMAGE_TAG_homelab_9000_boots_api}}@{{.IMAGE_DIGEST_homelab_9000_boots_api}}'
      - name: web
        chartPath: apps/web/k8s
        namespace: boots
        useHelmSecrets: true
        setValueTemplates:
          image.repository: homelab:9000/boots-web
          image.tag: '{{.IMAGE_TAG_homelab_9000_boots_web}}@{{.IMAGE_DIGEST_homelab_9000_boots_web}}'

test:
  - image: api
    structureTests:
      - 'apps/api/test/structure.test.yaml'
  - image: web
    structureTests:
      - 'apps/web/test/structure.test.yaml'

# verify:
#   - name: test-e2e
#     container:
#       image: '{{.IMAGE_NAME_test-e2e}}'
#       name: test-e2e

profiles:
  - name: dev
    activation:
      - command: dev
    patches:
      - op: remove
        path: /test

      - op: add
        path: /deploy/helm/releases/0/skipBuildDependencies
        value: true

      # dev api config
      - op: replace
        path: /build/artifacts/1/docker/dockerfile
        value: docker/Dockerfile.dev
      - op: replace
        path: /build/artifacts/1/docker/target
        value: dev-api
      - op: add
        path: /deploy/helm/releases/1/setValues
        value:
          health.enabled: false

      # dev web config
      - op: replace
        path: /build/artifacts/2/docker/dockerfile
        value: docker/Dockerfile.dev
      - op: replace
        path: /build/artifacts/2/docker/target
        value: dev-web
      - op: add
        path: /deploy/helm/releases/2/setValues
        value:
          health.enabled: false
  # - name: ci
  #   activation:
  #     - env: CI=true
  #   patches:
  #     - op: add
  #       path: /build/artifacts/-
  #       value:
  #         image: test-e2e
  #         docker:
  #           dockerfile: tests/e2e/Dockerfile
  #           cacheFrom: [test-e2e]
