apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: boots-cluster-issuer
  namespace: boots
spec:
  acme:
    email: boots.4.good@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # server: {{ .Values.issuer.acme.server }}
    privateKeySecretRef:
      name: boots-cluster-issuer-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: gateway
                namespace: boots
                kind: Gateway
