apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "boots-static.fullname" . }}
  labels:
    {{- include "boots-static.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.port | quote }}
  PORT_HEALTH: {{ .Values.health.port | quote }}
  