apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ include "boots-api.fullname" . }}-secrets"
  labels:
    {{- include "boots-api.labels" . | nindent 4 }}
stringData:
  JWT_AUTH_SECRET: "ref+sops://k8s/secrets.yaml#/JWT_AUTH_SECRET"

  POSTGRES_PASSWORD: "ref+sops://k8s/secrets.yaml#/POSTGRES_PASSWORD"

  REDIS_PASSWORD: "ref+sops://k8s/secrets.yaml#/REDIS_PASSWORD"

  GOOGLE_APPLICATION_CREDENTIALS: "ref+sops://k8s/secrets.yaml#/API_GOOGLE_APPLICATION_CREDENTIALS"

  FIREBASE_NOTIFICATION_DATABASE_URL: "ref+sops://k8s/secrets.yaml#/FIREBASE_NOTIFICATION_DATABASE_URL"
